// <auto-generated />
using System;
using Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TaskManager.Presentation.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230912221143_initialdb")]
    partial class initialdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Domain.Models.UserTask", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = new Guid("b9bee19b-c112-4f93-95ad-47b5de317292"),
                            Description = "Gym workout",
                            DueDate = new DateOnly(2023, 11, 10),
                            Priority = 2,
                            Status = 1,
                            Title = "Fitness Goals"
                        },
                        new
                        {
                            TaskId = new Guid("35f77619-97c7-48d5-a420-239677d88289"),
                            Description = "Research industry trends",
                            DueDate = new DateOnly(2023, 10, 12),
                            Priority = 2,
                            Status = 2,
                            Title = "Work Project Task"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
